id: P005562
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 12:02:44.494783
source_metadata:
  id: bdr:W1KG12961
  title: གླེགས་བམ་རིན་པོ་ཆེ་དགོས་འདོད་ཀུན་འབྱུང་།
  author: ''
  volumes:
    1b708433529b4003955793caf0570f23:
      image_group_id: I2PD16877
      title: ''
      volume_number: 1
      total_pages: 1184
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
